# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
markdown:            kramdown
#relative_permalinks: true

# Setup
title:               RN Financial Research Centre
#tagline:             'A Jekyll theme'
description:         RN Financial Research Centre
url:                 https://github.com/rnfc/rnfc.github.io
baseurl:             ''
paginate:            5
github:
  repo:              https://github.com/rnfc/rnfc.github.io

# About/contact
author:
  name:              RN Financial Research Centre
  url:               http://www.rnfc.org
  email:             rafael_nicolas@rnfc.org

# Custom vars
version:             1.0.0
website:			 http://www.rnfc.org
courses:			 /courses
blog:				 /blog

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# This is the list of pages to incldue in the header of the website.
pages_list:       ['About', 'Contact']

# Highlighter  
highlighter: rouge